# Generated by Django 4.2.18 on 2025-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_alter_course_teacher_alter_feedback_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
