# Generated by Django 4.2.18 on 2025-01-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_material_video_url_alter_material_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses_app.material'),
        ),
        migrations.RemoveField(
            model_name='progress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='progress_percentage',
        ),
    ]
