# Generated by Django 4.2.18 on 2025-01-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_alter_progress_unique_together_progress_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses_app.material'),
        ),
    ]
