# Generated by Django 4.2.18 on 2025-01-27 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0006_statusupdate_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='course',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
