# Generated by Django 4.2.18 on 2025-02-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
